# Generated by Django 3.0.4 on 2020-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=100)),
                ('postal', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=30)),
            ],
        ),
    ]
