# Generated by Django 3.2.9 on 2021-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uid_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
