# Generated by Django 3.2.9 on 2021-11-25 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0003_products_uid_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='uid_number',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
