# Generated by Django 3.2.9 on 2021-11-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0004_auto_20211125_1159'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='eval1_products',
        ),
    ]
