# Generated by Django 3.2.9 on 2021-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0005_alter_products_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_name', models.TextField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('ingredients', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('order_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
