# Generated by Django 3.2.9 on 2021-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='adress',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
