# Generated by Django 3.2.9 on 2021-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0007_auto_20211126_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='phone',
            field=models.TextField(max_length=100),
        ),
    ]
